REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('48','73');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('48','72');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('48','68');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('48','67');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('48','66');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('56','67');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('51','67');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('52','66');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('53','72');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('53','68');
Insert into EXPORT_TABLE (FK_PERFIL,FK_FUNCIONALIDADE) values ('53','66');
