/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  j129-9
 * Created: 18/10/2016
 */

-- Oracle cannot change the start value of a sequence.
-- Must drop and re-create.
-- Exclusão de todas as sequences do schema
SET SERVEROUTPUT ON;

--Gera para output os comandos create sequence
DECLARE
  tablename VARCHAR2(50 CHAR);
  sequencename VARCHAR2(50 CHAR);
  createSeqInstruction VARCHAR2(512);
  selectLastInstruction VARCHAR2(512);
  colExists NUMBER := 0;
  lastId NUMBER := 0;
  CURSOR myTables IS 
    SELECT ut.table_name AS tname FROM USER_TABLES ut;
BEGIN
  
  --Bye Tables!
  FOR i IN myTables LOOP
    tablename := i.tname;
    sequencename := tablename || '_SEQ';
    SELECT COUNT(*) INTO colExists FROM USER_TAB_COLS WHERE table_name = tablename AND column_name = 'ID';
    IF (colExists >0) THEN
      EXECUTE IMMEDIATE 'SELECT MAX(ID) FROM ' || i.tname INTO lastId;  
      IF (lastId IS NULL) THEN
        lastId:= 1;
      ELSE
        lastId := lastId + 1;
      END IF;
      createSeqInstruction := 'CREATE SEQUENCE '|| sequencename || ' START WITH ' || TO_CHAR(lastId) || ' INCREMENT BY 1;';                          
      DBMS_OUTPUT.PUT_LINE (createSeqInstruction);      
    END IF;
  END LOOP;
END;


CREATE SEQUENCE ALOCACAO_SEQ START WITH 19 INCREMENT BY 1;
CREATE SEQUENCE CALFERIADO_SEQ START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE CALFERIADOIT_SEQ START WITH 6 INCREMENT BY 1;
CREATE SEQUENCE CARGOOUFUNCAO_SEQ START WITH 7 INCREMENT BY 1;
CREATE SEQUENCE COLABORADOR_SEQ START WITH 11 INCREMENT BY 1;
CREATE SEQUENCE CONTAVINCULADA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONTRATO_SEQ START WITH 9 INCREMENT BY 1;
CREATE SEQUENCE ENCARGO_SEQ START WITH 13 INCREMENT BY 1;
CREATE SEQUENCE ENCARGOALIQUOTA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ENDERECO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ENDERECOELETRONICO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FATURAMENTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FATURAMENTOIT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FATURAMENTOITEVT_SEQ START WITH 9 INCREMENT BY 1;
CREATE SEQUENCE FISCAL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FISCALESPECIE_SEQ START WITH 6 INCREMENT BY 1;
CREATE SEQUENCE GLOSA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE GLOSAESPECIE_SEQ START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE JORNADA_SEQ START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE LIBERACAO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PESSOA_SEQ START WITH 1131 INCREMENT BY 1;
CREATE SEQUENCE POSTODETRABALHO_SEQ START WITH 17 INCREMENT BY 1;
CREATE SEQUENCE RAT_SEQ START WITH 5 INCREMENT BY 1;
CREATE SEQUENCE RATITEM_SEQ START WITH 17 INCREMENT BY 1;
CREATE SEQUENCE RETENCAO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SALARIO_SEQ START WITH 17 INCREMENT BY 1;
CREATE SEQUENCE TELEFONE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HT_RECURSO_SEQ START WITH 1 INCREMENT BY 1;