//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import br.jus.trt23.contavinculada.constraints.VigenciaUnicaNoContexto;
import java.util.AbstractMap;
import java.util.AbstractMap.SimpleEntry;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Table(schema = Constantes.SCHEMA)
@SequenceGenerator(name = "ID", sequenceName = "ALOCACAO_SEQ", allocationSize = 1, schema=Constantes.SCHEMA)
@Getter
@Setter
@RequiredArgsConstructor
@VigenciaUnicaNoContexto
public class Alocacao extends EntidadeGenerica implements IEntidadeQueDefineOContexto{
    protected final static String[] uniqueIndex = {"titular", "substituto", "postoDeTrabalho"};

    @ManyToOne
    @JoinColumn(nullable = false)
    private Colaborador titular;

    @ManyToOne
    @JoinColumn
    private Colaborador substituto;

    @ManyToOne
    @JoinColumn(nullable = false)    
    private PostoDeTrabalho postoDeTrabalho; 

    @Override
    public String getNomeNatural() {
        return "Alocação";
    }

    @Override
    public AbstractMap.SimpleEntry<String, EntidadeGenerica> getContexto() {
        return new SimpleEntry("postoDeTrabalho",getPostoDeTrabalho());
    }

    
    
}
