//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.enums.EFeriadoEscopo;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
@Table(
    uniqueConstraints = 
            @UniqueConstraint(columnNames={"vigenteDesde", "vigenteAte", "nome"})            
)
public class CalendarioFeriadoItem extends EntidadeGenerica {

    @Column(nullable = false)
    private String nome;

    private LocalDate quando;

    private EFeriadoEscopo escopo;
    
    private String onde;

    @Override
    public String toString() {
        return getNome();
    }
    
    

}
