//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(schema = Constantes.SCHEMA,
        uniqueConstraints
        = @UniqueConstraint(columnNames = {"vigenteDesde", "vigenteAte", "nome"})
)
public class CalendarioFeriado extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"nome"};

    @Getter
    @OneToMany(mappedBy = "feriadoCalendario")
    private List<PostoDeTrabalho> postosDeTrabalho;

    @Getter
    @Setter
    @NotEmpty
    private String nome;

    @Getter
    @OneToMany(cascade = {CascadeType.PERSIST, CascadeType.REFRESH, CascadeType.MERGE})
    private List<CalendarioFeriadoItem> feriados;

    @Getter
    @Setter
    @NotEmpty
    private String descricao;

    public CalendarioFeriado() {
        this.feriados = new ArrayList<>();
        this.postosDeTrabalho = new ArrayList<>();
    }

    public void addFeriados(CalendarioFeriadoItem item){
        feriados.add(item);
    }

    public void AddPostosDeTrabalho(PostoDeTrabalho posto) {
            postosDeTrabalho.add(posto);
            posto.setFeriadoCalendario(this);
    }    

    @Override
    public String toString() {
        return getNome();
    }

    @Override
    public String getNomeNatural() {
        return "Calendário de feriados";
    }

}
