//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Data;

@Entity
@Data
@Table(
    uniqueConstraints = 
            @UniqueConstraint(columnNames={"vigenteDesde", "vigenteAte", "nome"})            
)
public class CargoOuFuncao extends EntidadeGenerica {

    @Column(nullable = false)
    private String nome;

    @OneToMany(targetEntity = PostoDeTrabalho.class, mappedBy = "cargoOuFuncao")
    private List<PostoDeTrabalho> postosDeTrabalho;

    private String descricao;

    private String atribuicoes;

}
