//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constraints.VigenciaValida;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(
        uniqueConstraints
        = @UniqueConstraint(columnNames = {"vigenteDesde", "vigenteAte", "nome"})
)
@VigenciaValida
public class CargoOuFuncao extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"nome"};
    @Getter
    @Setter
    @NotEmpty
    private String nome;

    @Getter
    @Setter
    @NotEmpty
    private String descricao;

    @Getter
    @Setter
    @NotEmpty
    private String atribuicoes;

    @Getter
    @OneToMany(targetEntity = PostoDeTrabalho.class, mappedBy = "cargoOuFuncao")
    private List<PostoDeTrabalho> postosDeTrabalho;

    public CargoOuFuncao() {
        this.postosDeTrabalho = new ArrayList<>();
    }

    public void addPostosDeTrabalho(PostoDeTrabalho posto){
        postosDeTrabalho.add(posto);
        posto.setCargoOuFuncao(this);
    }
    
    @Override
    public String toString() {
        return getNome();
    }

}
