//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.time.LocalDate;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
@Table(
    uniqueConstraints = 
            @UniqueConstraint(columnNames={"vigenteDesde", "vigenteAte", "empregador_id", "colaborador_id"})            
)
public class Colaborador extends EntidadeGenerica {


    @ManyToOne
    @JoinColumn(nullable=false)    
    private PessoaJuridica empregador;
    
    @ManyToOne
    @JoinColumn(nullable=false)        
    private PessoaFisica colaborador;
    
    private Boolean isDesligamentoPorJustaCausa;

    private LocalDate recebeuManualEm;

    private String responsavelTecnico;

    @OneToMany(mappedBy = "colaborador")
    private List<Alocacao> alocacoes;
    
    @OneToMany(mappedBy = "substituto")
    private List<FaturamentoItem> substituicoes;   

    @OneToMany(mappedBy = "colaborador")
    private List<Retencao> retencoes;    
}
