//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.time.LocalDate;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class Colaborador extends EntidadeGenerica {


    @ManyToOne(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinColumn(nullable=false)    
    private PessoaJuridica empregador;
    
    @NotNull
    @ManyToOne(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinColumn(nullable=false)        
    private PessoaFisica colaborador;
    
    private Boolean isDesligamentoPorJustaCausa;

    private LocalDate recebeuManualEm;

    private String responsavelTecnico;

    @OneToMany(mappedBy = "titular")
    private List<Alocacao> titularEm;
    
    @OneToMany(mappedBy = "substituto")
    private List<Alocacao> substitutoEm;

    @OneToMany(mappedBy = "substituto")
    private List<FaturamentoItem> substituicoes;   

    @OneToMany(mappedBy = "colaborador")
    private List<Retencao> retencoes; 
    
    @OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
    private List<Salario> salarios;
    
    @Override
    public String toString(){
        return getColaborador().toString();
    }
}
