//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import br.jus.trt23.contavinculada.constraints.VigenciaEstritaAoContrato;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;


@Entity
@Getter
@Setter
@RequiredArgsConstructor
@Table(schema = Constantes.SCHEMA,
    uniqueConstraints = 
            @UniqueConstraint(columnNames={"banco", "agencia", "conta", "operacao"})            
)
@VigenciaEstritaAoContrato
public class ContaVinculada extends EntidadeGenerica implements IEscopoRestritoAoContrato{
    protected final static String[] uniqueIndex = {"contrato", "banco", "agencia", "conta","operacao"};
    
    @NotNull
    @ManyToOne
    private Contrato contrato;

    @NotEmpty
    @Column(nullable = false)
    private String banco;

    @NotEmpty
    @Column(nullable = false)
    private String agencia;

    @NotEmpty
    @Column(nullable = false)
    private String conta;

    private String operacao;    

    @Override
    public String getNomeNatural() {
        return "Conta vinculada";
    }
}
