//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.time.LocalDate;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Data;

@Entity
@Data
@Table(
    uniqueConstraints = 
            @UniqueConstraint(columnNames={"vigenteDesde", "vigenteAte", "numero"})            
)
public class Contrato extends EntidadeGenerica {

    @Column(nullable=false)
    private String numero;

    @ManyToOne
    private Contrato aditivoDe;

    @ManyToOne(targetEntity = Pessoa.class)
    @JoinColumn(nullable=false)        
    private Pessoa contratado;

    @Column(nullable=false)
    private String objeto;

    private LocalDate assinaturaData;

    @Lob
    private Byte[] inteiroTeor;

    private String processo;

    private String arp;

    private String regimeTributacao;

    @OneToOne
    private ContaVinculada contasVinculadas;

    @OneToMany(targetEntity = PostoDeTrabalho.class)
    private List<PostoDeTrabalho> postosDeTrabalho;

    @OneToMany(targetEntity = Faturamento.class)
    private List<Faturamento> faturamentos;

    @OneToMany(mappedBy = "aditivoDe")
    private List<Contrato> aditivos;

    @OneToMany(mappedBy = "contrato")
    private List<Fiscal> fiscais;

    @ManyToMany(mappedBy = "contratos")
    private List<EncargoAliquota> aliquotas;

    private String situacao;
}
