//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import javax.persistence.Entity;
import lombok.Data;

@Entity
@Data
public class Email extends EntidadeGenerica {

   private String email;

    private String descricao;

}
