//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import lombok.Getter;
import lombok.Setter;

@Entity
public class EncargoAliquota extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"contrato","encargo","aliquota"};
    @Getter
    @Setter
    @ManyToOne
    private Encargo encargo;

    @Getter
    @Setter
    private double aliquota;

    @Getter
    @Setter
    @ManyToOne
    private Contrato contrato;

    public EncargoAliquota() {

    }
}
