//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import lombok.Data;

@Entity
@Data
public class Encargo extends EntidadeGenerica{  
    private String nome;
    
    private Boolean isRetencaoContaVinculada;
    
    @OneToMany(mappedBy = "encargo")
    private List<EncargoAliquota> aliquota;    

}
