//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import javax.persistence.Entity;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class EnderecoEletronico extends EntidadeGenerica {

   @Email
    private String email;

   @NotEmpty
   private String descricao;

}
