//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import javax.persistence.Entity;
import javax.persistence.Table;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(schema = Constantes.SCHEMA)
@Getter
@Setter
@RequiredArgsConstructor
public class EnderecoEletronico extends EntidadeGenerica {

    protected final static String[] uniqueIndex = {"mail"};
    @Email
    private String email;

    @NotEmpty
    private String descricao;

    @Override
    public String getNomeNatural() {
        return "Endereço eletrônico";
    }
}
