//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import javax.persistence.Entity;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class Endereco extends EntidadeGenerica {
    private String uf;

    private String cidade;

    private String complemento;

    private String numero;

    private String logradouro;

    private String bairro;

    private String nome;

    private String cep;
}
