//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import javax.persistence.Entity;
import lombok.Data;

@Entity
@Data
public class FaturamentoItemEvento extends EntidadeGenerica {
    private String nome;
    private Boolean isSubstituicao;
}
