//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.time.LocalDate;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class Faturamento extends EntidadeGenerica {

    @OneToMany(mappedBy = "faturamento")
    private List<Retencao> retencoes;

    private LocalDate competencia;

    @ManyToOne
    private Contrato contrato;

    @Transient
    private String situacao;
    
    @OneToMany(mappedBy = "faturamento")
    private List<FaturamentoItem> itens;

    @OneToMany(targetEntity = Glosa.class, mappedBy = "faturamento")
    private List<Glosa> glosas;

    private String nfeOuFatura;

    private LocalDate atestadaEm;
    
    @ManyToOne
    private Fiscal atestadaPor;

    @Transient
    private Double valorLiquido;
    
    @Transient
    private Double valorBruto;
}
