//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Data;

@Entity
@Data
@Table(
    uniqueConstraints = 
            @UniqueConstraint(columnNames={"vigenteDesde", "vigenteAte", "nome"})            
)
public class FiscalEspecie extends EntidadeGenerica {
    

    @Column(nullable=false)
    private String nome;
    
    @OneToMany(targetEntity = Fiscal.class, mappedBy = "especie")
    private List<Fiscal> fiscais;
    

 }
