//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import lombok.Data;

@Entity
@Data
public class Fiscal extends EntidadeGenerica {
    @ManyToOne(targetEntity = FiscalEspecie.class)
    @JoinColumn(nullable=false)
    private FiscalEspecie especie;

    @Column(nullable=false)
    private String atoDesignacao;

    @ManyToOne
    @JoinColumn(nullable=false)
    private Servidor servidor;
    
    @ManyToOne
    @JoinColumn(nullable=false)
    private Contrato contrato;
    
    @OneToMany(mappedBy = "atestadaPor")
    private List<Faturamento> faturamentosAtestados;    
}
