//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(schema = Constantes.SCHEMA)
public class GlosaEspecie extends EntidadeGenerica {

    protected final static String[] uniqueIndex = {"nome"};
    
    @Getter
    @Setter
    private String nome;

    @Getter
    @OneToMany(targetEntity = Glosa.class, mappedBy = "especie")
    private List<Glosa> glosas;

    public GlosaEspecie() {
        this.glosas = new ArrayList<>();
    }

    public void addGlosas(Glosa glosa) {
        glosas.add(glosa);
        glosa.setEspecie(this);
    }

    @Override
    public String getNomeNatural() {
        return "Espécie de glosa";
    }
}
