//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Table(schema = Constantes.SCHEMA)
@Getter
@Setter
@RequiredArgsConstructor
@SequenceGenerator(name = "ID", sequenceName = "GLOSA_SEQ", allocationSize = 1, schema=Constantes.SCHEMA)
public class Glosa extends EntidadeGenerica{
    protected final static String[] uniqueIndex = {"glosa"};    
    private Integer qtd;

    @ManyToOne(targetEntity = GlosaEspecie.class)
    private GlosaEspecie especie;

    private String glosadoPor;

    @ManyToOne(targetEntity = Faturamento.class)
    private Faturamento faturamento;

    private String descricao;

    private Double valorUnitario;

    @Override
    public String getNomeNatural() {
        return "Glosa";
    }
}
