//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class Jornada extends EntidadeGenerica {

    @NotEmpty
    private String nome;

    @NotEmpty
    private String descricao;    

    @OneToMany(mappedBy = "jornada")
    private List<PostoDeTrabalho> postosDeTrabalho;

    @Override
    public String toString() {
        return getNome();
    }
    
    
}
