//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.Set;
import java.util.TreeSet;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
public class Jornada extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"nome"};        

    @Getter
    @Setter
    @NotEmpty
    private String nome;

    @Getter
    @Setter
    @NotEmpty
    private String descricao;

    @OneToMany(mappedBy = "jornada")
    private Set<PostoDeTrabalho> postosDeTrabalho;

    public Jornada() {
        this.postosDeTrabalho = new TreeSet<>();
    }

    public Set<PostoDeTrabalho> getPostosDeTrabalho() {
        return new TreeSet<>(postosDeTrabalho);
    }

    public void addPostosDeTrabalho(PostoDeTrabalho posto) {
        postosDeTrabalho.add(posto);
        posto.setJornada(this);
    }

    @Override
    public String toString() {
        return getNome();
    }

}
