//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(schema = Constantes.SCHEMA)
@SequenceGenerator(name = "ID", sequenceName = "JORNADA_SEQ", allocationSize = 1, schema=Constantes.SCHEMA)
public class Jornada extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"nome"};        

    @Getter
    @Setter
    @NotEmpty
    private String nome;

    @Getter
    @Setter
    @NotEmpty
    private String descricao;

    @Getter
    @OneToMany(mappedBy = "jornada")
    private List<PostoDeTrabalho> postosDeTrabalho;

    public Jornada() {
        this.postosDeTrabalho = new ArrayList<>();
    }

    public void addPostosDeTrabalho(PostoDeTrabalho posto) {
        postosDeTrabalho.add(posto);
        posto.setJornada(this);
    }

    @Override
    public String toString() {
        return getNome();
    }

    @Override
    public String getNomeNatural() {
        return "Jornada";
    }

}
