//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Table(schema = Constantes.SCHEMA)
@Getter
@Setter
@RequiredArgsConstructor
public class Liberacao extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"retencao"};        
    
    @Lob
    private Byte[] anexos;

    @OneToOne
    private Retencao retencao;

    private String liberadoPor;

    private String parecerLiberacao;

    @Override
    public String getNomeNatural() {
        return "Liberação";
    }

}
