//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMappings;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
@NamedNativeQueries({
    @NamedNativeQuery(name="getPessoaPorNomeOuRazaoSocial", query ="SELECT * FROM pessoa WHERE upper(nome) like '%:nome'% OR upper(razaoSocial) like '%:razaoSocial%'")
})
@SqlResultSetMappings({
})
public abstract class Pessoa extends EntidadeGenerica {
    @OneToMany(targetEntity = EnderecoEletronico.class)
    private List<EnderecoEletronico> emails;

    @OneToMany(targetEntity = Endereco.class)
    private List<Endereco> enderecos;

    @OneToMany(targetEntity = Contrato.class, mappedBy = "contratado")
    private List<Contrato> contratos;

    @OneToMany(targetEntity = Telefone.class)
    private List<Telefone> telefones;
    
    public abstract String getDescricao();
    
   @Override
   public String toString(){
       return getDescricao();
   } 
}
