//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public abstract class Pessoa extends EntidadeGenerica {

    @OneToMany(targetEntity = Email.class)
    private List<Email> emails;

    @OneToMany(targetEntity = Endereco.class)
    private List<Endereco> enderecos;

    @OneToMany(targetEntity = Contrato.class, mappedBy = "contratado")
    private List<Contrato> contratos;

    @OneToMany(targetEntity = Telefone.class)
    private List<Telefone> telefones;
    
    public abstract String getDescricao();
    
   @Override
   public String toString(){
       return getDescricao();
   } 
}
