//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class PessoaJuridica extends Pessoa  {
    private String cnpj;

    private String nomeFantasia;

    private String inscricaoEstadual;

    private String razaoSocial;
    
    @OneToMany(mappedBy = "empregador")
    private List<Colaborador> contratanteEm;

    @Override
    public String getDescricao() {
        return getNomeFantasia().concat(" (").concat(getRazaoSocial()).concat(")");
    }
    
    
}
