//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class PostoDeTrabalho extends EntidadeGenerica {

    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
    private Contrato contrato;
    @ManyToOne(targetEntity = CargoOuFuncao.class)
    private CargoOuFuncao cargoOuFuncao;
    
    @ManyToOne
    private Jornada jornada;
    
    @OneToMany(mappedBy = "postoDeTrabalho")
    private List<Alocacao> alocacoes;
    
    @OneToMany(mappedBy = "postoDeTrabalho")
    private List<FaturamentoItem> faturamentoItems;    
    
    public Alocacao getAlocacaoAtiva(){
        //TODO: Buscar a alocação ativa no momento
        return null;
    }
    
    public Alocacao getAlocacaoAtivaEntre(Date inicio, Date fim){
        //TODO: Buscar a alocação ativa em um período
        return null;
    }    
}
