//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import javax.persistence.Entity;
import javax.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
public class RAT extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"percentual"};
    @Getter
    @Setter
    @NotEmpty
    private String percentual;

    @Getter
    @Setter
    @NotNull
    private Double aliquotaRetencao;
   
    @Override
    public String toString() {
        return getPercentual();
    }

}
