//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(schema = Constantes.SCHEMA)
@SequenceGenerator(name = "ID", sequenceName = "RAT_SEQ", allocationSize = 1, schema=Constantes.SCHEMA)
public class RAT extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"percentual"};
    @Getter
    @Setter
    @NotEmpty
    private String percentual;

    @Getter
    @Setter
    @OneToMany(mappedBy = "rat",cascade = {CascadeType.PERSIST, CascadeType.REFRESH,CascadeType.MERGE})
    private List<RATItem> itens;

    public RAT() {
        itens=new ArrayList<>();
    }
    
    public void addItem(RATItem item){
        itens.add(item);
        item.setRat(this);        
    }
    
    @Override
    public String toString() {
        return getPercentual();
    }

    @Override
    public String getNomeNatural() {
        return "RAT";
    }

    
}
