//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Entity
public class RATItem extends EntidadeGenerica {
    protected final static String[] uniqueIndex = {"rat, encargo"};
    @Getter
    @Setter
    @NotNull
    @ManyToOne
    private RAT rat;
   
    @Getter
    @Setter
    @NotNull
    @ManyToOne
    private Encargo encargo;
    
    @Getter
    @Setter
    @NotNull
    private Double aliquota;    

    @Getter
    @Setter
    @OneToMany(mappedBy = "ratItem",cascade = {CascadeType.MERGE,CascadeType.PERSIST,CascadeType.REFRESH})
    private List<Retencao> retencoes;
    
    @Override
    public String toString() {
        return getEncargo().toString() + " ("+ getAliquota().toString() + ")";
    }

    @Override
    public String getNomeNatural() {
        return "Item RAT";
    }

}
