//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(schema = Constantes.SCHEMA)
@SequenceGenerator(name = "ID", sequenceName = "RETENCAO_SEQ", allocationSize = 1, schema=Constantes.SCHEMA)
public class Retencao extends EntidadeGenerica{

    protected final static String[] uniqueIndex = {"faturamento", "colaborador", "ratItem"};

    public Retencao() {
        this.faturamentoItens = new ArrayList<>();
    }

    @Getter
    @Setter
    @NotNull
    @ManyToMany(cascade = {CascadeType.MERGE,CascadeType.PERSIST,CascadeType.REFRESH})
    private List<FaturamentoItem> faturamentoItens;

    @Getter
    @Setter
    @NotNull
    @ManyToOne
    private Colaborador colaborador;

    @Getter
    @Setter
    @NotNull
    @ManyToOne(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    private RATItem ratItem;

    @Getter
    @Setter
    @NotNull
    private Double salario;

    @Getter
    @Setter
    private Integer diasSubstituicao;

    @Getter
    @Setter
    private Integer diasTitularidade;

    @Transient
    private Double fatorTrabalhadoNoPeriodo;

    @Transient
    private Integer diasNoPeriodo;

    @Transient
    private Double retido;
    
    @Getter
    @Setter
    @ManyToOne(cascade = {CascadeType.MERGE,CascadeType.PERSIST,CascadeType.REFRESH})
    @NotNull
    private Faturamento faturamento;

    @Getter
    @Setter
    @OneToOne(mappedBy = "retencao",cascade = {CascadeType.MERGE,CascadeType.PERSIST,CascadeType.REFRESH})
    private Liberacao liberacao;

    public Double getRetido() throws Exception {
        if(null == retido){
            retido = (ratItem.getAliquota()/100) * salario * getFatorTrabalhadoNoPeriodo();
        }
        return retido;
    }

    public Integer getDiasNoPeriodo() throws Exception {
        if (null == diasNoPeriodo) {
            if (faturamentoItens.size() > 0) {
                diasNoPeriodo = faturamentoItens.get(0).getFaturamento().getDiasEntreReferencias();
            } else {
                throw new Exception("Não há faturamento associado à retenção.");
            }
        }
        return diasNoPeriodo;
    }

    public Double getFatorTrabalhadoNoPeriodo() throws Exception {
        if (null == fatorTrabalhadoNoPeriodo) {
            fatorTrabalhadoNoPeriodo = (diasSubstituicao.doubleValue() + diasTitularidade.doubleValue()) / getDiasNoPeriodo().doubleValue();
        }
        return fatorTrabalhadoNoPeriodo;
    }

    @Override
    public String getNomeNatural() {
        return "Retenção";
    }
}
