//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(schema = Constantes.SCHEMA)
public class Servidor extends PessoaFisica {
    protected final static String[] uniqueIndex = {"matricula"};    
    
    @Getter
    @Setter
    @NotEmpty
    private String matricula;

    @Getter
    @OneToMany(mappedBy = "servidor")
    private List<Fiscal> fiscais;

    public Servidor() {
        this.fiscais = new ArrayList<>();
    }

    public void addFiscais(Fiscal fiscal) {
        fiscais.add(fiscal);
        fiscal.setServidor(this);
    }

    @Override
    public String getNomeNatural() {
        return "Servidor";
    }

    
}
