//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.contavinculada.entities;

import br.jus.trt23.contavinculada.constants.Constantes;
import javax.persistence.Entity;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(schema = Constantes.SCHEMA)
@Getter
@Setter
@RequiredArgsConstructor
@SequenceGenerator(name = "ID", sequenceName = "TELEFONE_SEQ", allocationSize = 1, schema=Constantes.SCHEMA)
public class Telefone extends EntidadeGenerica {

    @NotEmpty
    private String tipo;

    @NotEmpty
    @Pattern(regexp = "(\\(\\d{2,3}\\)")
    private String ddd;
    
    @NotEmpty    
    @Pattern(regexp = "\\d{2,3})([-\\s]?\\d{4}){2}")
    private String numero;

    @Override
    public String getNomeNatural() {
        return "Telefone";
    }
}
